---
- name: Virtual nodes provisioning | Generate inventory based on group_vars
  hosts: localhost
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
    - "group_vars/{{ cloud_name }}/vsphere_infra.yml"
  roles:
    - generate-host-groups


- name: SSH keys | Generate public key on master nodes
  hosts:
    - master_nodes
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
  tasks:
    - name: KVM | Make sure the SSH key exists
      user:
        name: root
        generate_ssh_key: yes


    - name: SSH keys | Take the key
      fetch:
        src: "/root/.ssh/id_rsa.pub"
        dest: /tmp/.rsync.pub
        flat: yes
      changed_when: false



- name: SSH keys | Setup SSH keys
  hosts:
    - master_nodes
    - worker_nodes
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
  tasks:
  - name: Insert the key
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/tmp/.rsync.pub') }}"

- name: Install dependencies
  hosts:
    - k8s_nodes
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
    - "group_vars/{{ cloud_name }}/kubernetes_cluster.yml"
  roles:
    - { role: docker, tags: docker }

- name: Deploy cluster on master node
  hosts:
    - master_nodes
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
    - "group_vars/{{ cloud_name }}/kubernetes_cluster.yml"
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }


- name: Deploy cluster on worker nodes
  hosts:
    - worker_nodes
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
    - "group_vars/{{ cloud_name }}/kubernetes_cluster.yml"
  roles:
    - { role: kubernetes/node, tags: node }


- pause:
    seconds: 30
