#k8s nodes parameters

virtual_k8s_nodes:

  master1:
    vm_hostname: master.local
    vm_management_ip: 192.168.1.160
    vm_disk_size_gb: 40
    vm_memory_mb: 8092
    vm_number_vcpus: 2


  worker1:
    vm_hostname: worker1.local
    vm_management_ip: 192.168.1.161
    vm_disk_size_gb: 40
    vm_memory_mb: 4096
    vm_number_vcpus: 2


  worker2:
    vm_hostname: worker2.local
    vm_management_ip: 192.168.1.162
    vm_disk_size_gb: 40
    vm_memory_mb: 4096
    vm_number_vcpus: 2


  loadbalancer1:
    vm_hostname: loadbalancer1.local
    vm_management_ip: 192.168.1.163
    vm_disk_size_gb: 40
    vm_memory_mb: 2048
    vm_number_vcpus: 1



#VM Management network variables
vm_management_netmask: 255.255.255.0
vm_gateway: 192.168.1.1
vm_dns_server: '8.8.8.8'

#VM default vSphere options
vm_guest_id: 'rhel7_64Guest'
vm_guest_template: 'centos_gold'
vm_guest_notes: 'Managed by Ansible'
vm_domain_name: "local"
vm_mgmt_interface: ens192
vm_template_ip: 192.168.1.240

#Nginx repo
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
