- name: Create inentory for ESXi host
  add_host:
    hostname: "{{ esxi_ip }}"
    management_ip: "{{ esxi_ip }}"
    groups: esxi
  changed_when: false



- name: Create inentory for k8s nodes
  add_host:
    hostname: "{{ item.value.vm_management_ip }}"
    management_ip: "{{ item.value.vm_management_ip }}"
    groups: k8s_nodes
  become: yes
  become_user: root
  with_dict: "{{ virtual_k8s_nodes }}"
  changed_when: false


- name: Create inventory for LoadBalancer hosts
  add_host:
    name: "{{ item.value.vm_management_ip }}"
    groups: loadbalancer_nodes
    management_ip: "{{ item.value.vm_management_ip }}"
  become: yes
  become_user: root
  with_dict: "{{ virtual_k8s_nodes }}"
  when: "'loadbalancer' in item.key"
  changed_when: false
