---
- name: Virtual nodes provisioning | Generate inventory based on group_vars
  hosts: localhost
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
    - "group_vars/{{ cloud_name }}/vsphere_infra.yml"
  roles:
    - generate-host-groups

- name: Install dependencies
  hosts:
    - k8s_nodes
  vars_files:
    - "group_vars/{{ cloud_name }}/k8s_virtual_nodes.yml"
    - "group_vars/{{ cloud_name }}/kubernetes_cluster.yml"
  roles:
    - { role: docker, tags: docker }
